language: go

go: stable

before_install:
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - dep ensure

script:
  go test ./...

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true