language: go

go: stable

before_install: go get -t ./...

script:
  go test ./...


deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true