language: go

go: tip

gobuild_args: -ldflags "-X main.Version=${TRAVIS_TAG} -X main.BuildTime=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X main.CommitId=${TRAVIS_COMMIT}"

before_install: go get -t ./...

install: go build -o passw0rd

script:
  go test ./...

before_deploy:
- PLATFORMS=(darwin/386 darwin/amd64 freebsd/386 freebsd/amd64 freebsd/arm linux/386 linux/amd64 linux/arm windows/386 windows/amd64)

# build binary for all archs
- |
  for PLATFORM in "${PLATFORMS[@]}"; do
    echo "Building $PLATFORM"
    GOOS=${PLATFORM%/*}
    GOARCH=${PLATFORM#*/}

    if [ "$GOOS" = "windows" ]; then
      build_cmd="GOOS=$GOOS GOARCH=$GOARCH go build -o passw0rd -ldflags '-w -s'"
    else
      build_cmd="CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -o passw0rd -ldflags '-d -w -s'"
    fi
    if ! eval $build_cmd; then
      echo "Failed building passw0rd for $PLATFORM" && return 1
    fi

    if [ "$GOOS" = "windows" ]; then
      zip passw0rd-${GOOS}-${GOARCH}.zip passw0rd
    else
      tar cvzf passw0rd-${GOOS}-${GOARCH}.tgz passw0rd
    fi
  done

- ls

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  file:
  - "passw0rd-darwin-386.tgz"
  - "passw0rd-darwin-amd64.tgz"

  - "passw0rd-freebsd-386.tgz"
  - "passw0rd-freebsd-arm.tgz"
  - "passw0rd-freebsd-amd64.tgz"

  - "passw0rd-linux-386.tgz"
  - "passw0rd-linux-arm.tgz"
  - "passw0rd-linux-amd64.tgz"

  - "passw0rd-windows-386.zip"
  - "passw0rd-windows-amd64.zip"

  skip_cleanup: true
  on:
    tags: true