// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterResponse struct {
	ConfirmationSessionToken string   `protobuf:"bytes,1,opt,name=confirmation_session_token,json=confirmationSessionToken,proto3" json:"confirmation_session_token,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetConfirmationSessionToken() string {
	if m != nil {
		return m.ConfirmationSessionToken
	}
	return ""
}

type ConfirmAccountRequest struct {
	Email                    string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmationSessionToken string   `protobuf:"bytes,2,opt,name=confirmation_session_token,json=confirmationSessionToken,proto3" json:"confirmation_session_token,omitempty"`
	ConfirmationCode         string   `protobuf:"bytes,3,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	Password                 string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *ConfirmAccountRequest) Reset()         { *m = ConfirmAccountRequest{} }
func (m *ConfirmAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmAccountRequest) ProtoMessage()    {}
func (*ConfirmAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{2}
}

func (m *ConfirmAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmAccountRequest.Unmarshal(m, b)
}
func (m *ConfirmAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmAccountRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmAccountRequest.Merge(m, src)
}
func (m *ConfirmAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmAccountRequest.Size(m)
}
func (m *ConfirmAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmAccountRequest proto.InternalMessageInfo

func (m *ConfirmAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ConfirmAccountRequest) GetConfirmationSessionToken() string {
	if m != nil {
		return m.ConfirmationSessionToken
	}
	return ""
}

func (m *ConfirmAccountRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

func (m *ConfirmAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ConfirmAccountResponse struct {
	QrUrl                string   `protobuf:"bytes,1,opt,name=qr_url,json=qrUrl,proto3" json:"qr_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmAccountResponse) Reset()         { *m = ConfirmAccountResponse{} }
func (m *ConfirmAccountResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmAccountResponse) ProtoMessage()    {}
func (*ConfirmAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{3}
}

func (m *ConfirmAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmAccountResponse.Unmarshal(m, b)
}
func (m *ConfirmAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmAccountResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmAccountResponse.Merge(m, src)
}
func (m *ConfirmAccountResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmAccountResponse.Size(m)
}
func (m *ConfirmAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmAccountResponse proto.InternalMessageInfo

func (m *ConfirmAccountResponse) GetQrUrl() string {
	if m != nil {
		return m.QrUrl
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Totp                 string   `protobuf:"bytes,3,opt,name=totp,proto3" json:"totp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetTotp() string {
	if m != nil {
		return m.Totp
	}
	return ""
}

type LoginResponse struct {
	AccountToken         string   `protobuf:"bytes,1,opt,name=account_token,json=accountToken,proto3" json:"account_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAccountToken() string {
	if m != nil {
		return m.AccountToken
	}
	return ""
}

type Application struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AppToken             string   `protobuf:"bytes,4,opt,name=app_token,json=appToken,proto3" json:"app_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{6}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Application) GetAppToken() string {
	if m != nil {
		return m.AppToken
	}
	return ""
}

type CreateAppRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAppRequest) Reset()         { *m = CreateAppRequest{} }
func (m *CreateAppRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAppRequest) ProtoMessage()    {}
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{7}
}

func (m *CreateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppRequest.Unmarshal(m, b)
}
func (m *CreateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppRequest.Marshal(b, m, deterministic)
}
func (m *CreateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppRequest.Merge(m, src)
}
func (m *CreateAppRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAppRequest.Size(m)
}
func (m *CreateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppRequest proto.InternalMessageInfo

func (m *CreateAppRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateAppResponse struct {
	App                  *Application `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateAppResponse) Reset()         { *m = CreateAppResponse{} }
func (m *CreateAppResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAppResponse) ProtoMessage()    {}
func (*CreateAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{8}
}

func (m *CreateAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppResponse.Unmarshal(m, b)
}
func (m *CreateAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppResponse.Marshal(b, m, deterministic)
}
func (m *CreateAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppResponse.Merge(m, src)
}
func (m *CreateAppResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAppResponse.Size(m)
}
func (m *CreateAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppResponse proto.InternalMessageInfo

func (m *CreateAppResponse) GetApp() *Application {
	if m != nil {
		return m.App
	}
	return nil
}

type AccountApplicationsResponse struct {
	App                  []*Application `protobuf:"bytes,1,rep,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AccountApplicationsResponse) Reset()         { *m = AccountApplicationsResponse{} }
func (m *AccountApplicationsResponse) String() string { return proto.CompactTextString(m) }
func (*AccountApplicationsResponse) ProtoMessage()    {}
func (*AccountApplicationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{9}
}

func (m *AccountApplicationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountApplicationsResponse.Unmarshal(m, b)
}
func (m *AccountApplicationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountApplicationsResponse.Marshal(b, m, deterministic)
}
func (m *AccountApplicationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountApplicationsResponse.Merge(m, src)
}
func (m *AccountApplicationsResponse) XXX_Size() int {
	return xxx_messageInfo_AccountApplicationsResponse.Size(m)
}
func (m *AccountApplicationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountApplicationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountApplicationsResponse proto.InternalMessageInfo

func (m *AccountApplicationsResponse) GetApp() []*Application {
	if m != nil {
		return m.App
	}
	return nil
}

type UpdateTokenResponse struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	UpdateToken          []byte   `protobuf:"bytes,2,opt,name=update_token,json=updateToken,proto3" json:"update_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTokenResponse) Reset()         { *m = UpdateTokenResponse{} }
func (m *UpdateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTokenResponse) ProtoMessage()    {}
func (*UpdateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{10}
}

func (m *UpdateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTokenResponse.Unmarshal(m, b)
}
func (m *UpdateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTokenResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTokenResponse.Merge(m, src)
}
func (m *UpdateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTokenResponse.Size(m)
}
func (m *UpdateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTokenResponse proto.InternalMessageInfo

func (m *UpdateTokenResponse) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UpdateTokenResponse) GetUpdateToken() []byte {
	if m != nil {
		return m.UpdateToken
	}
	return nil
}

type HttpError struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpError) Reset()         { *m = HttpError{} }
func (m *HttpError) String() string { return proto.CompactTextString(m) }
func (*HttpError) ProtoMessage()    {}
func (*HttpError) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{11}
}

func (m *HttpError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpError.Unmarshal(m, b)
}
func (m *HttpError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpError.Marshal(b, m, deterministic)
}
func (m *HttpError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpError.Merge(m, src)
}
func (m *HttpError) XXX_Size() int {
	return xxx_messageInfo_HttpError.Size(m)
}
func (m *HttpError) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpError.DiscardUnknown(m)
}

var xxx_messageInfo_HttpError proto.InternalMessageInfo

func (m *HttpError) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HttpError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "models.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "models.RegisterResponse")
	proto.RegisterType((*ConfirmAccountRequest)(nil), "models.ConfirmAccountRequest")
	proto.RegisterType((*ConfirmAccountResponse)(nil), "models.ConfirmAccountResponse")
	proto.RegisterType((*LoginRequest)(nil), "models.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "models.LoginResponse")
	proto.RegisterType((*Application)(nil), "models.Application")
	proto.RegisterType((*CreateAppRequest)(nil), "models.CreateAppRequest")
	proto.RegisterType((*CreateAppResponse)(nil), "models.CreateAppResponse")
	proto.RegisterType((*AccountApplicationsResponse)(nil), "models.AccountApplicationsResponse")
	proto.RegisterType((*UpdateTokenResponse)(nil), "models.UpdateTokenResponse")
	proto.RegisterType((*HttpError)(nil), "models.HttpError")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573) }

var fileDescriptor_0b5431a010549573 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0xd6, 0x51, 0xc8, 0x6d, 0x2a, 0x3a, 0x8f, 0xa1, 0x68, 0x13, 0x12, 0x18, 0xf1, 0x21,
	0x21, 0x0d, 0x09, 0x78, 0x01, 0xf1, 0x52, 0x15, 0x24, 0x24, 0x78, 0x40, 0x66, 0x7b, 0xae, 0xbc,
	0xe4, 0x52, 0x45, 0x4b, 0xe2, 0x5b, 0xdb, 0x61, 0xea, 0xff, 0xe2, 0x07, 0xa2, 0xd8, 0x4e, 0x9b,
	0x82, 0xc8, 0x9e, 0xea, 0xeb, 0x7b, 0xee, 0x39, 0xe7, 0x9e, 0x3a, 0x90, 0x54, 0x2a, 0xc7, 0xd2,
	0x9c, 0x93, 0x56, 0x56, 0xb1, 0xb1, 0xaf, 0xf8, 0x0b, 0xb8, 0x2f, 0x70, 0x55, 0x18, 0x8b, 0x5a,
	0xe0, 0xba, 0x41, 0x63, 0xd9, 0x03, 0xb8, 0x83, 0x95, 0x2c, 0xca, 0x34, 0x7a, 0x1c, 0xbd, 0x8c,
	0x85, 0x2f, 0xf8, 0x77, 0x98, 0xed, 0x80, 0x86, 0x54, 0x6d, 0x90, 0x7d, 0x84, 0xd3, 0x4c, 0xd5,
	0x3f, 0x0b, 0x5d, 0x49, 0x5b, 0xa8, 0x7a, 0x69, 0xd0, 0x98, 0xf6, 0xd7, 0xaa, 0x6b, 0xac, 0xc3,
	0x78, 0xda, 0x47, 0xfc, 0xf0, 0x80, 0x8b, 0xb6, 0xcf, 0x7f, 0x47, 0x70, 0xb2, 0xf0, 0xcd, 0x79,
	0x96, 0xa9, 0xa6, 0xb6, 0x83, 0x0e, 0x6e, 0x51, 0x3b, 0x18, 0x56, 0x63, 0xaf, 0xe0, 0x68, 0x6f,
	0x3a, 0x53, 0x39, 0xa6, 0x23, 0x37, 0x34, 0xeb, 0x37, 0x16, 0x2a, 0x47, 0x76, 0x0a, 0xf7, 0x48,
	0x1a, 0x73, 0xa3, 0x74, 0x9e, 0x1e, 0x3a, 0xcc, 0xb6, 0xe6, 0xaf, 0xe1, 0xe1, 0xdf, 0xae, 0x43,
	0x1c, 0x27, 0x30, 0x5e, 0xeb, 0x65, 0xa3, 0xb7, 0xbe, 0xd7, 0xfa, 0x52, 0x97, 0xfc, 0x02, 0x92,
	0x6f, 0x6a, 0x55, 0xd4, 0xc3, 0xdb, 0xf5, 0x25, 0x0f, 0xf6, 0x25, 0x19, 0x83, 0x43, 0xab, 0x2c,
	0x05, 0xbb, 0xee, 0xcc, 0xdf, 0xc1, 0x34, 0xb0, 0x06, 0xf5, 0xa7, 0x30, 0x95, 0xde, 0xd0, 0x5e,
	0xfe, 0x49, 0xb8, 0xf4, 0x99, 0xdf, 0xc0, 0x64, 0x4e, 0x54, 0x16, 0x99, 0xdb, 0x95, 0xa5, 0x70,
	0xf7, 0x17, 0xea, 0x36, 0x24, 0x87, 0x9e, 0x8a, 0xae, 0x6c, 0x25, 0x6b, 0x59, 0x61, 0xb0, 0xe2,
	0xce, 0xec, 0x11, 0x00, 0x35, 0x57, 0x65, 0x91, 0x2d, 0xaf, 0x71, 0xe3, 0xcc, 0x24, 0x22, 0xf6,
	0x37, 0x5f, 0x71, 0xc3, 0xce, 0x20, 0x96, 0x44, 0x41, 0x3c, 0xa4, 0x26, 0x89, 0xbc, 0xf0, 0x73,
	0x98, 0x2d, 0x34, 0x4a, 0x8b, 0x73, 0xa2, 0x2e, 0x88, 0x4e, 0x23, 0xda, 0x69, 0xf0, 0x0f, 0x70,
	0xd4, 0xc3, 0x85, 0xd5, 0x9e, 0xc1, 0x48, 0x12, 0x39, 0xdc, 0xe4, 0xcd, 0xf1, 0x79, 0x78, 0xc8,
	0xbd, 0x45, 0x44, 0xdb, 0xe7, 0x9f, 0xe0, 0x2c, 0xfc, 0x25, 0xbd, 0x96, 0xf9, 0x97, 0x65, 0x34,
	0xc8, 0x22, 0xe0, 0xf8, 0x92, 0x72, 0x69, 0xd1, 0x19, 0xdf, 0x4e, 0xff, 0x3f, 0xaa, 0x27, 0x90,
	0x34, 0x6e, 0xa0, 0xf7, 0x12, 0x13, 0x31, 0x69, 0x76, 0x24, 0xfc, 0x3d, 0xc4, 0x5f, 0xac, 0xa5,
	0xcf, 0x5a, 0x2b, 0xdd, 0xae, 0xed, 0x1e, 0x9f, 0xa7, 0x71, 0xe7, 0x96, 0xbd, 0x42, 0x63, 0xe4,
	0xaa, 0x4b, 0xbc, 0x2b, 0xaf, 0xc6, 0xee, 0x7b, 0x7d, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd3,
	0xbd, 0x94, 0x07, 0xbf, 0x03, 0x00, 0x00,
}
